### ISSUE TITLE
Server on local machine ran out of buffer space

### ISSUE THREAD

**Issue by acmcpheron02** [StrangeLoopGames/EcoSuggestions#496]
I'm running the Eco Server v7.2.6 from Steam on my local Windows 10 machine (v1803 Insider build) and received the following error multiple times. The program is installed on my SSD and I have 16gb ram. This game is only for myself and someone else on LAN, so we've only had two users at most. This is the only message logged following server initialization and is repeated numerous times per second. Trying to log on later caused the error again but with a new timestamp.

[09:13:09] Server Initialization finished in 104,042.3ms
[04:25:06] Failed to send packet: System.Net.Sockets.SocketException (0x80004005): An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full
   at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP)
   at Lidgren.Network.NetPeer.SendPacket(Int32 numBytes, IPEndPoint target, Int32 numMessages, Boolean& connectionReset)

Just let me know if you need additional details!

**Comment by D3nnis3n** [comment]
This should have been in the issue tracker, as it seems like a bug. I'm assuming it's fixed since it's been over a year since then, but if this issue arises again, please open an issue on our bugtracker :)
