### ISSUE TITLE
Exception in server logs since 0.8.0.3 BETA

### ISSUE THREAD

**Issue by DalaryousPT** [StrangeLoopGames/EcoSuggestions#700]
Not sure about the actual impact but found the following exception being repeated in our server logs since 0.8.0.3 BETA:

[11:38:12] Exception when updating object SteamTractorObject: Sequence contains no elements
at System.Linq.Enumerable.First[TSource](IEnumerable1 source)
at Eco.Mods.TechTree.SteamTractorSowerItem.BlockInteraction(Vector3i pos, Quaternion rot, VehicleComponent vehicle, Inventory inv)
at Eco.Gameplay.Components.ModularVehicleComponent.OnVehicleMoved()
at Eco.Gameplay.Components.VehicleComponent.ReceiveUpdate(BSONObject bsonObj)
at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable1 enumeration, Action`1 action)
at Eco.Gameplay.Objects.WorldObject.ReceiveUpdate(BSONObject bsonObj)
at Eco.Shared.Networking.NetObjectManager.UpdateObjects(BSONObject bsonRoot)

**Comment by johnkslg** [comment]
Thanks, moving to eco issues instead of suggestions
